version: '3'
services:
  app:
    container_name: weather_config
    build: . # dir where Dockerfile is located
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    #depends_on:
      # - fullstack-postgres          # Uncomment this when using postgres.
      # - fullstack-mysql           # Uncomment this when using mysql.
    networks:
      - fullstack

# from https://github.com/elevennines-inc/swagger-all-in-one-docker-compose/blob/master/docker-compose.yml
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./swagger-ui.yaml:/api.yaml
    environment:
      SWAGGER_JSON: /api.yaml
      # API_URL: ""
    networks:
      - fullstack

  # fullstack-mysql:
  #   image: mysql:5.7
  #   container_name: full_db_mysql
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_HOST=${DB_HOST}
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - database_mysql:/var/lib/mysql
  #   networks:
  #     - fullstack

volumes:
  api:
  # database_postgres:                # Uncomment this when using postgres.
  # database_mysql:                   # Uncomment this when using mysql.

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge