version: '3'

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge

services:
  app:
    container_name: app
    build: . # dir where Dockerfile is located

    # ports : Activates the container to listen for specified port(s) from the world outside of the docker
    # (can be same host machine or a different machine) AND also accessible world inside docker.
    ports:
      - 8080:8080
    #restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mongodb-service
      # - fullstack-postgres        # Uncomment this when using postgres.
      # - fullstack-mysql           # Uncomment this when using mysql.
    environment:
      MONGO_DB: weatherIntegDb
      WEATHER_BINDING_PORT: 8080
    networks:
      - fullstack

# from https://github.com/elevennines-inc/swagger-all-in-one-docker-compose/blob/master/docker-compose.yml
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./swagger-ui.yaml:/api.yaml
    environment:
      SWAGGER_JSON: /api.yaml
      # API_URL: ""
    depends_on:
      - app
    networks:
      - fullstack

  mongodb-service:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PWD}
      #MONGO_INITDB_DATABASE: ${MONGO_INITDB}
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - fullstack

  # fullstack-mysql:
  #   image: mysql:5.7
  #   container_name: full_db_mysql
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_HOST=${DB_HOST}
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - database_mysql:/var/lib/mysql
  #   networks:
  #     - fullstack

volumes:
  api:
  # database_postgres:                # Uncomment this when using postgres.
  # database_mysql:                   # Uncomment this when using mysql.
