{
  "swagger": "2.0",
  "info": {
    title: "Sample REST Api",
    description: "API to get locations and regions for weather UI",
    version: "0.0.1",
  },
  basePath: "/v1",
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  definitions: {
    Region: {
      properties: {
        name: {
          type: string,
          description: "unique identifier for region"
        },
        searchKey: {
          type: string,
          description: "key used in searches on WTA",
        },
        description: {
          type: string,
          description: "descriptive region label",
        },
      },
      example: {
        name: "central_cascades",
        searchKey: "12345567",
        description: "Central Cascades",
      }

    },
    Location: {
      properties: {
        name: {
          type: string,
          description: ""
        },
        region: {
          type: string,
          description: ""
        },
        description: {
          type: string,
          description: ""
        },
        latitude: {
          type: number,
          format: float64,
          description: ""
        },
        longitude: {
          type: number,
          format: float64,
          description: ""
        },
        subRegion: {
          type: string,
          description: ""
        }
      },
      example: {
        name: "gold bar",
        region: "centraol_cascades",
        description: "Stevents Pass - West",
        latitude: 47.8090,
        longitude: -121.5738,
        subRegion: "12344555",
      }
    }
  },

  "paths": {
    "/locations": {
      "get": {
        "description": "Finds a location set",
        "tags": [
          "locations"
        ],
        "operationId": "findLocations",
        "responses": {
          "200": {
            description: "OK",
            schema: {
              type: array,
              items: {
                "$ref": "#/definitions/Location"
              }
            },
          }
        }
      }
    },
    "/regions": {
      "get": {
        "description": "Finds a region set",
        "tags": [
          "regions"
        ],
        "operationId": "findRegions",
        "responses": {
          "200": {
            description: "OK",
            schema: {
              type: array,
              items: {
                "$ref": "#/definitions/Region"
              }
            }
          }
        }
      }
    }
  },

}